### ISSUE TITLE
关于HKO-7数据集

### ISSUE THREAD

**Issue by wintercoming233** [mazhf/MS-RNN#2]
请问一下您的HKO-7数据集是怎样处理的？radar_png和mask_png如何使用？

**Comment by rongtongxueya** [comment]
您好，可以交流一下吗，我也有同样的困扰，不知道这个数据集怎么放

**Comment by wintercoming233** [comment]
可以，897198138@qq.com

**Comment by mazhf** [comment]
@wintercoming233 @rongtongxueya 
我认为原始预处理HKO-7的代码过于复杂（https://github.com/Hzzone/Precipitation-Nowcasting），另外在模型训练和度量等各个阶段都需要考虑掩码的问题，这复杂化了Precipitation Nowcasting，我建议大家像minist一样直接使用原始图片构建整体代码。这不会影响对比模型的性能。

**Comment by wintercoming233** [comment]
@mazhf 了解，感谢马兄回复

**Comment by wintercoming233** [comment]
@mazhf  我想问一下您PrecipLSTM文中用到的巴西雷达数据集在哪里可以获取？
